services:
  app:
    container_name: insuranceproject-app
    build:
      context: .
      dockerfile: Dockerfile
    image: insuranceproject-node:latest
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: "3000"
      DATABASE_URL: ${DATABASE_URL}
      PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING: "1"
      PRISMA_ALLOW_INSECURE_TLS: "1"
    ports:
      - "3000:3000"
    restart: unless-stopped
